### ISSUE TITLE
2.2.2 getByEmailLastName - but you just query All the Tourist without any filters. Add filters (names, emails)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [polashkind/sf-senla-courses#14]
https://github.com/polashkind/sf-senla-courses/blob/bc6fa9e778bd62901abf68f773d4e9f00a31fd6e/Lecture_2.2/TouristService.cls#L4

**Comment by polashkind** [comment]
Done

**Comment by NikitaErmakSenla** [comment]
This code can not be compiled or saved:
`TouristManager.getByEmailAndLastName(Set<String> newEmails, Set<String> newNames);`
