### ISSUE TITLE
2.3.2 Move to Constants class

### ISSUE THREAD

**Issue by NikitaErmakSenla** [polashkind/sf-senla-courses#21]
https://github.com/polashkind/sf-senla-courses/blob/bc6fa9e778bd62901abf68f773d4e9f00a31fd6e/Lecture_2.3/TouristService.cls#L27

**Comment by polashkind** [comment]
@NikitaErmakSenla Can I use Enum?

**Comment by NikitaErmakSenla** [comment]
Enum (in Constants) is even more preferable way to keep picklist values.

So yes. But it's a little harder to do

**Comment by NikitaErmakSenla** [comment]
Still relevant

**Comment by polashkind** [comment]
Done
